### PR TITLE
ops: setting up docker compose

### PR DESCRIPTION
**Pull request by j-koziel**

### CODE REVIEW

**Comment by j-koziel** [comment]
When I run the docker compose command (`docker compose up`), it fails with the error below.

image

**Comment by j-koziel** [comment]
Also need to figure out a way to have test containers without exposing username/password to the DB which are defined in `application.properties`

**Comment by j-koziel** [comment]
btw, @JudeDavis1 for your testing remember to make a `docker-compose.yml` file in the docker dir because the one that's in the repo is the example. Just copy the contents of the example into the file which will be used by docker

**Review by JudeDavis1 — CHANGES_REQUESTED** [review]
Sorry for the late review. You forgot to add the Dockerfile path to the YAML. This may not fix the problem but will make it easier to pinpoint

**Comment by JudeDavis1** [comment]
Also, don't put the YAML in the `docker/` directory, put it in the root. I've done it.

**Comment by JudeDavis1** [comment]
Build should work now 👍

**Comment by JudeDavis1** [comment]
`docker compose build` in root

**Review by JudeDavis1 — APPROVED** [review]

**Comment by j-koziel** [comment]
@JudeDavis1 It's still not working for me.... I am getting the same error as before. I am running `docker compose build` in root. I get this error message.

image

**Comment by j-koziel** [comment]
I feel like its not copying everything over for some reason.... maybe the postgres image is overwriting some stuff in `home/appuser/`?

I'll try running it without the postgres image.

**Comment by j-koziel** [comment]
Nevermind for some reason the dockerfile path wasnt transferred from the example config to the actual config

**Comment by JudeDavis1** [comment]
> Also need to figure out a way to have test containers without exposing username/password to the DB which are defined in `application.properties`

@j-koziel the DB linked locally (in the docker-compose) is a test DB. It is not one that's used in production. The one used in production is seperate.

**Comment by j-koziel** [comment]
> > Also need to figure out a way to have test containers without exposing username/password to the DB which are defined in `application.properties`
> 
> @j-koziel the DB linked locally (in the docker-compose) is a test DB. It is not one that's used in production. The one used in production is seperate.

Sorry I just saw this.... ok that sounds good but we will still have to figure out how to hide those details in production.... I'm guessing we can just exclude those files when we merge dev/prod branches and just use our own one in the prod branch?

Do you think this is a viable solution @JudeDavis1?

**Comment by JudeDavis1** [comment]
> > > Also need to figure out a way to have test containers without exposing username/password to the DB which are defined in `application.properties`
> 
> > 
> 
> > @j-koziel the DB linked locally (in the docker-compose) is a test DB. It is not one that's used in production. The one used in production is seperate.
> 
> 
> 
> Sorry I just saw this.... ok that sounds good but we will still have to figure out how to hide those details in production.... I'm guessing we can just exclude those files when we merge dev/prod branches and just use our own one in the prod branch?
> 
> 
> 
> Do you think this is a viable solution @JudeDavis1?

So we don’t have static data. We have a program (called a seeder) to insert test data at first. In production, we have live data. However, since we don’t have stuff like usernames accounts etc. we just have a tree of bible verses. So we might not _really_ need separate seeders.

**Comment by JudeDavis1** [comment]
> > > > Also need to figure out a way to have test containers without exposing username/password to the DB which are defined in `application.properties`
> > 
> > > 
> > 
> > > @j-koziel the DB linked locally (in the docker-compose) is a test DB. It is not one that's used in production. The one used in production is seperate.
> > 
> > 
> > 
> > Sorry I just saw this.... ok that sounds good but we will still have to figure out how to hide those details in production.... I'm guessing we can just exclude those files when we merge dev/prod branches and just use our own one in the prod branch?
> > 
> > 
> > 
> > Do you think this is a viable solution @JudeDavis1?
> 
> So we don’t have static data. We have a program (called a seeder) to insert test data at first. In production, we have live data. However, since we don’t have stuff like usernames accounts etc. we just have a tree of bible verses. So we might not _really_ need separate seeders. 

The seeder is the thing that decides what to put in a dev-db or prod-db

**Pull request merged**
