### PR TITLE
Created the react app

### PR DESCRIPTION
**Pull request by j-koziel**
So I did it a bit differently than how I said I would. Instead of making a views folder I made two different folders: backend and frontend. So one folder for each separate app. Could you check if everything is in order and if there is something that should be changed in the way I did this?

### CODE REVIEW

**Comment by j-koziel** [comment]
We probably have to modify our generator scripts with the folder changes but that is an easy fix

**Comment by JudeDavis1** [comment]
Exactly what I was thinking, the frontend and backend should be separate probably. I'll take a look 👌

**Comment by JudeDavis1** [comment]
Should I clean up the project a bit, removing redundant tests and stuff, they just get in the way. As we discussed, maybe we should include tests at a later stage, but for now, the boilerplate reactjs tests are redundant.

**Comment by JudeDavis1** [comment]
Are you okay with me clearing it up a bit?

**Comment by JudeDavis1** [comment]
I'll commit it, but if there is a problem we can always revert.

**Comment by j-koziel** [comment]
> Are you okay with me clearing it up a bit?

yup go ahead

**Comment by JudeDavis1** [comment]
did you add the node_modules for the frontend to the root .gitignore?

**Review by j-koziel — COMMENTED** [review]
everything looks good to me

**Comment by j-koziel** [comment]
> did you add the node_modules for the frontend to the root .gitignore?

yeah it's all there... I added the files mentioned in the gitignore for the react app to the root gitignore so that we only needed one file

**Review by j-koziel — COMMENTED** [review]
cool... thanks

**Comment by JudeDavis1** [comment]
good to mark the TODO as completed?

**Comment by j-koziel** [comment]
> good to mark the TODO as completed?

yes

**Comment by JudeDavis1** [comment]
Ok. LGTM for merging

**Pull request merged**
