### PR TITLE
Frontend routing

### PR DESCRIPTION
**Pull request by JudeDavis1**
The client-side routing for the UI.

### CODE REVIEW

**Comment by JudeDavis1** [comment]
What routes should we use? e.g: /home

I would presume /home is a must.

**Comment by JudeDavis1** [comment]
Also, will the react app have multiple pages e.g. /home, and other routes?

**Comment by JudeDavis1** [comment]
And I'm also thinking to add a Navbar

**Comment by JudeDavis1** [comment]
I can add that to TODO.md if you like

**Review by j-koziel — APPROVED** [review]
looks good to me

**Comment by j-koziel** [comment]
changed base to dev-frontend

**Pull request merged**
