### PR TITLE
ci(java-mig): create dockerfile

### PR DESCRIPTION
**Pull request by j-koziel**

### CODE REVIEW

**Comment by JudeDavis1** [comment]
@j-koziel Tested?

**Comment by j-koziel** [comment]
im getting an error... 

image

**Comment by j-koziel** [comment]
build image works but running the container this happens

**Comment by JudeDavis1** [comment]
What command are you using? To run the dockerfile

**Comment by j-koziel** [comment]
im just using the docker plugin in intellij... so it runs some command for me but im not sure what it is exactly

**Comment by JudeDavis1** [comment]
`docker run docker` in the root

**Comment by j-koziel** [comment]
i think that command is wrong... i get a "docker: invalid reference format"

**Comment by JudeDavis1** [comment]
Sorry my bad.. You need to rename the container image

**Comment by j-koziel** [comment]
to?

**Comment by JudeDavis1** [comment]
@j-koziel I have improved the Dockerfile a bit. Script in there too. (remember to `pull`)

Sorry for the late developments I had work

**Comment by JudeDavis1** [comment]
Just run in the root dir:

`sh ./docker/start.sh`

**Comment by j-koziel** [comment]
doesn't work.... says that access to the requested resource is denied

**Comment by j-koziel** [comment]
running the start.sh script doesn't work, but running it from intellij does work

**Comment by j-koziel** [comment]
i think i might use heroku instead... just easier for now

**Comment by j-koziel** [comment]
I will likely reopen this at a later time

**Pull request merged**
