### PR TITLE
Route generation

### PR DESCRIPTION
**Pull request by JudeDavis1**

### CODE REVIEW

**Comment by JudeDavis1** [comment]
To test the code, just: `git checkout jude-contrib`
Then run: `npm run create-route {routeName}`

If all is good, please merge into dev for me, thanks.

**Review by j-koziel — APPROVED** [review]
Good work, thank you. 👌

**Comment by j-koziel** [comment]
will test tomorrow but it looks good to me

**Comment by JudeDavis1** [comment]
Thanks 👍

**Comment by JudeDavis1** [comment]
I could write some unit tests for things like this if needed to make our life easier

**Comment by j-koziel** [comment]
> I could write some unit tests for things like this if needed to make our life easier

I think for now the size of the project doesn't require it... could you just explain a bit what you mean by unit tests.. just so that we're on the same page 👍

**Comment by JudeDavis1** [comment]
Just a small script to make sure that a component of the application works as intended, but yeah you may be right

**Comment by j-koziel** [comment]
> Just a small script to make sure that a component of the application works as intended, but yeah you may be right

Yeah we can probably consider it later but for now I think we should probably focus on getting the core functionality running and focus on stuff like refactoring/optimization/testing at a later stage of the project

**Comment by JudeDavis1** [comment]
Good idea

**Comment by j-koziel** [comment]
Im going to close this because I merged into dev from the command line. I didn't realise you could change the base branch on here until just now... 🤦‍♂️ anyways it should all be there in dev.

**Comment by JudeDavis1** [comment]
Thanks 👍

**Pull request closed without merging**
