### PR TITLE
refactor: using layered design pattern

### PR DESCRIPTION
**Pull request by JudeDavis1**
Using the Service/View/DTO design pattern

### CODE REVIEW

**Comment by JudeDavis1** [comment]
I know this works, I would just like to get into the habit of PR-oriented version control.

Why? When collabing, it is easier to keep track of code that goes in and out and helps the collaborators to understand what is going on. And it also helps to have a second set of eyes 👀. Something to consider.

Also - don't merge yet, I will do a rebase. Just look over my code and approve if LGTU.

**Review by j-koziel — CHANGES_REQUESTED** [review]
the code is good, however i think it would make more sense to call the folder "bibleVerses" instead of "getVerse" because we include all the bible verse endpoints here

**Comment by JudeDavis1** [comment]
Oh yeah my bad, I was on autopilot 😅

**Comment by JudeDavis1** [comment]
Tests are broken - can fix in a future PR

**Pull request merged**
