### PR TITLE
Updating to version 0.1.0

### PR DESCRIPTION
**Pull request by j-koziel**
I'm going to begin versioning the API as I add more and more features. Let me know if this looks ok to you.

### CODE REVIEW

**Comment by j-koziel** [comment]
Just resolved some conflicts.

**Review by j-koziel — COMMENTED** [review]
Just double checking I didn't do something stupid 😂

**Comment by JudeDavis1** [comment]
LGTM.

**Comment by JudeDavis1** [comment]
@j-koziel merge?

**Pull request merged**
